
name: mCloud Infra
on:
#   schedule:
#     - cron:  '1 4 * * 1-5'
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Your Project Name'
        default: 'mcloud'
      environment:
        description: 'Project env'
        default: 'dev'
      playbook:
        description: 'Enter Playbook name'
        default: 'lemp'
      options:
        description: 'Provide you ansible options'
        default: '-t base,user_mgmt -CD'
        
jobs:
  mCloud-Infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        #working-directory: /opt
        shell: bash
    env:
     GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
     #ANSIBLE_HOST_KEY_CHECKING: False
     ANSIBLE_CONFIG: "${GITHUB_WORKSPACE}/mcloud-ansible/inventory/ansible.cfg"
     ANSIBLE_INVENTORY: "inventory/hosts_${{ github.event.inputs.project_name }}"
     ANSIBLE_ROLES_PATH: ${GITHUB_WORKSPACE}/mcloud-ansible/playbook/roles:~/.ansible/roles
     ANSIBLE_WORKING_DIR: mcloud-infra/ansible
     ANSIBLE_OPTIONS: ${{ github.event.inputs.options }}
     TARGET_HOST: ${{ github.event.inputs.project_name }}_${{ github.event.inputs.environment }}
     ANSIBLE_PLAYBOOK: ${{ github.event.inputs.playbook }}.yml
     ANSIBLE_EXTRA_VARS: "project_environment=${{ github.event.inputs.project_name }} env_name=${{ github.event.inputs.environment }}"
     
             
    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
#       - name: Checkout ${ANSIBLE_WORKING_DIR} 
#         uses: actions/checkout@v2.4.0
#         with:
#           repository: HarryTheDevOpsGuy/mCloud-Users
#           path: mcloud-users
#           ref: main
#           ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      - name: info 
        run: |
          hostname
          hostname -I
          curl ifconfig.me
          free -h
          df -h
          ansible --version
          pip3 install prettytable
          pip install prettytable
  
      - name: mproject clone ${{ env.ANSIBLE_WORKING_DIR }}
        run: |
          git clone -b master git@bitbucket.org:devopsexpert/mcloud-infra.git ${GITHUB_WORKSPACE}/mcloud-infra
          git clone -b master git@bitbucket.org:devopsexpert/mcloud-ansible.git ${GITHUB_WORKSPACE}/mcloud-ansible
          
      - name: Run ansible playbook
        working-directory: ${{ env.ANSIBLE_WORKING_DIR }}
        run: |
           [[ -f "${ANSIBLE_INVENTORY}" ]] || export ANSIBLE_INVENTORY="/etc/ansible/hosts"
           ansible-galaxy install -r ${GITHUB_WORKSPACE}/mcloud-ansible/playbook/ansible-pull-requirements.yml
           ansible-playbook -e "target_host=127.0.0.1" lemp.yml -t 'user_create' -vv
           #ansible-playbook -u harry -e "target_host=${TARGET_HOST} ${ANSIBLE_EXTRA_VARS}" "${{ env.ANSIBLE_OPTIONS }}" ${ANSIBLE_PLAYBOOK}
           hostname
